//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountorTransectionValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountorTransectionValue()
        {
            this.Transections = new HashSet<Transection>();
            this.Transections1 = new HashSet<Transection>();
        }
    
        public int AccountorTransectionValueId { get; set; }
        public string AccountorTransectionValueName { get; set; }
        public Nullable<int> AccountorTransectionTypeId { get; set; }
    
        public virtual AccountorTransectionType AccountorTransectionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transection> Transections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transection> Transections1 { get; set; }
    }
}
