//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankServer
    {
        public int BankServerId { get; set; }
        public Nullable<int> CustomerAccountManageId { get; set; }
        public Nullable<int> TransectionId { get; set; }
        public Nullable<int> CreditCardDetailID { get; set; }
        public Nullable<int> LoanID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual CreditCardDetail CreditCardDetail { get; set; }
        public virtual CustomerAccountManage CustomerAccountManage { get; set; }
        public virtual Loan Loan { get; set; }
        public virtual Transection Transection { get; set; }
    }
}
