//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditCardDetail()
        {
            this.BankServers = new HashSet<BankServer>();
        }
    
        public int CreditCardDetailID { get; set; }
        public Nullable<int> CardNumber { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public Nullable<int> CardLimit { get; set; }
        public Nullable<int> CustomerInformationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankServer> BankServers { get; set; }
        public virtual CustomerInformation CustomerInformation { get; set; }
    }
}
