//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccountManage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerAccountManage()
        {
            this.BankServers = new HashSet<BankServer>();
            this.Loans = new HashSet<Loan>();
            this.Transections = new HashSet<Transection>();
        }
    
        public int CustomerAccountManageId { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<int> AccountBalance { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CustomerInformationId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankServer> BankServers { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual CustomerInformation CustomerInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transection> Transections { get; set; }
    }
}
