//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.BankServers = new HashSet<BankServer>();
            this.LoanPayments = new HashSet<LoanPayment>();
        }
    
        public int LoanID { get; set; }
        public Nullable<int> LoanType { get; set; }
        public Nullable<int> LoanNumber { get; set; }
        public Nullable<int> IssuedLoanAmount { get; set; }
        public Nullable<int> RemainingLoanAmmount { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CustomerAccountManageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankServer> BankServers { get; set; }
        public virtual CustomerAccountManage CustomerAccountManage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanPayment> LoanPayments { get; set; }
    }
}
