//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankingSystemEntities1 : DbContext
    {
        public BankingSystemEntities1()
            : base("name=BankingSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccountorTransectionType> AccountorTransectionTypes { get; set; }
        public virtual DbSet<AccountorTransectionValue> AccountorTransectionValues { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankServer> BankServers { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CreditCardDetail> CreditCardDetails { get; set; }
        public virtual DbSet<CustomerAccountManage> CustomerAccountManages { get; set; }
        public virtual DbSet<CustomerInformation> CustomerInformations { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<LoanPayment> LoanPayments { get; set; }
        public virtual DbSet<Transection> Transections { get; set; }
    }
}
